// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD964HYaXzcwFINYPUtBSAtv3b0PoyjkrY',
    appId: '1:346151105515:web:6925c8561228c6163a9fae',
    messagingSenderId: '346151105515',
    projectId: 'findscanreturn',
    authDomain: 'findscanreturn.firebaseapp.com',
    storageBucket: 'findscanreturn.appspot.com',
    measurementId: 'G-473PSK53KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADkuJWF9F7MkBt7jZvcCEyBlXDUigmBAg',
    appId: '1:346151105515:android:f15977b720ac68e13a9fae',
    messagingSenderId: '346151105515',
    projectId: 'findscanreturn',
    storageBucket: 'findscanreturn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQpcs7M1X_AGiURK5l4kfLHhqNICAAEAM',
    appId: '1:346151105515:ios:804e2a6a9f10dfac3a9fae',
    messagingSenderId: '346151105515',
    projectId: 'findscanreturn',
    storageBucket: 'findscanreturn.appspot.com',
    androidClientId: '346151105515-v1gnd6dkmvb6valiornavu580u092su4.apps.googleusercontent.com',
    iosClientId: '346151105515-jtnuott08700mecol32rb7nihv2ile3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.findScanReturnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQpcs7M1X_AGiURK5l4kfLHhqNICAAEAM',
    appId: '1:346151105515:ios:7c8b9a4f9293b91b3a9fae',
    messagingSenderId: '346151105515',
    projectId: 'findscanreturn',
    storageBucket: 'findscanreturn.appspot.com',
    androidClientId: '346151105515-v1gnd6dkmvb6valiornavu580u092su4.apps.googleusercontent.com',
    iosClientId: '346151105515-lorul0kvfs74ha9rp3ac64ucensdpr8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.findScanReturnApp.RunnerTests',
  );
}
